name: Post to Mastodon

on:
  push:
    branches:
      - main

jobs:
  post_to_mastodon:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get the latest commit timestamp
        id: get_commit_time
        run: echo "COMMIT_TIME=$(git log -1 --pretty=%ct)" >> $GITHUB_ENV

      - name: Find posts with Mastodon flag and valid timestamp
        id: find_flagged_posts
        run: |
          FLAGGED_POSTS=$(grep -rl '^post_to_mastodon: true' _posts)

          if [ -z "$FLAGGED_POSTS" ]; then
            echo "No posts flagged for Mastodon. Exiting."
            exit 0
          fi

          POST_URLS=""
          for POST in $FLAGGED_POSTS; do
            # Attempt to get date from front matter
            POST_TIMESTAMP=$(grep '^date:' "$POST" | head -n 1 | sed 's/date: //' | xargs -I{} date -d "{}" +%s || true)

            # Fallback to file name if no date field is found
            if [ -z "$POST_TIMESTAMP" ]; then
              POST_DATE=$(basename "$POST" | cut -d'-' -f1-3)
              POST_TIMESTAMP=$(date -d "$POST_DATE" +%s)
            fi

            echo "Checking post: $POST"
            echo "Post timestamp (Unix): $POST_TIMESTAMP"

            # Compare post timestamp to the latest commit time
            if [ "$POST_TIMESTAMP" -ge "$COMMIT_TIME" ]; then
              URL="https://www.pntaylor.net/$(basename ${POST%.*}).html"
              POST_URLS+="$URL"$'\n'
              echo "Post $POST is eligible for posting."
            else
              echo "Post $POST is too old."
            fi
          done

          if [ -z "$POST_URLS" ]; then
            echo "No posts with valid timestamps found. Exiting."
            exit 0
          fi

          echo "POST_URLS=$POST_URLS" >> $GITHUB_ENV

      - name: Post to Mastodon
        if: env.POST_URLS != ''
        run: |
          for URL in $(echo "$POST_URLS"); do
            toot post "New blog post: $URL"
          done
