name: Post to Bluesky

on:
  push:
    branches:
      - main

jobs:
  post_to_bluesky:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get the latest commit timestamp
        id: get_commit_time
        run: echo "COMMIT_TIME=$(git log -1 --pretty=%ct)" >> $GITHUB_ENV

      - name: Find posts with Bluesky flag and valid timestamp
        id: find_flagged_posts
        run: |
          FLAGGED_POSTS=$(grep -rl '^post_to_socials: true' _posts)

          if [ -z "$FLAGGED_POSTS" ]; then
            echo "No posts flagged for Bluesky. Exiting."
            exit 0
          fi

          POST_URLS=""
          for POST in $FLAGGED_POSTS; do
            POST_DATE=$(grep '^date:' "$POST" | head -n 1 | sed 's/date: //' | cut -d' ' -f1 || true)
            if [ -z "$POST_DATE" ]; then
              POST_DATE=$(basename "$POST" | cut -d'-' -f1-3)
            fi
            COMMIT_DATE=$(date -d "@$COMMIT_TIME" +"%Y-%m-%d")

            if [ "$POST_DATE" == "$COMMIT_DATE" ]; then
              URL="https://www.pntaylor.net/blog/$(basename ${POST%.*} | sed 's/^[0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}-//')"
              POST_URLS+="$URL"$'\n'
            fi
          done

          if [ -z "$POST_URLS" ]; then
            echo "No posts with valid timestamps found. Exiting."
            exit 0
          fi

          echo "POST_URLS=$POST_URLS" >> $GITHUB_ENV

      - name: Install Bluesky CLI (bsky-cli)
        run: |
          sudo apt-get update
          sudo apt-get install -y npm
          npm install -g bsky-cli

      - name: Log in to Bluesky CLI
        env:
          BLUESKY_USERNAME: ${{ secrets.BLUESKY_USERNAME }}
          BLUESKY_PASSWORD: ${{ secrets.BLUESKY_PASSWORD }}
        run: |
          bsky login --username "$BLUESKY_USERNAME" --password "$BLUESKY_PASSWORD"

      - name: Post to Bluesky
        if: env.POST_URLS != ''
        run: |
          for URL in $(echo "$POST_URLS"); do
            bsky post "New blog post: $URL"
          done
