name: Post to Mastodon

on:
  push:
    branches:
      - main

jobs:
  post_to_mastodon:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get the latest commit timestamp
        id: get_commit_time
        run: echo "COMMIT_TIME=$(git log -1 --pretty=%ct)" >> $GITHUB_ENV

      - name: Find posts with Mastodon flag and valid timestamp
        id: find_flagged_posts
        run: |
          FLAGGED_POSTS=$(grep -rl '^post_to_mastodon: true' _posts)

          if [ -z "$FLAGGED_POSTS" ]; then
            echo "No posts flagged for Mastodon. Exiting."
            exit 0
          fi

          POST_URLS=""
          for POST in $FLAGGED_POSTS; do
            # Attempt to get date from front matter
            POST_DATE=$(grep '^date:' "$POST" | head -n 1 | sed 's/date: //' | cut -d' ' -f1 || true)

            # Fallback to file name if no date field is found
            if [ -z "$POST_DATE" ]; then
              POST_DATE=$(basename "$POST" | cut -d'-' -f1-3)
            fi

            # Get commit date (only the date portion, no time)
            COMMIT_DATE=$(date -d "@$COMMIT_TIME" +"%Y-%m-%d")

            echo "Checking post: $POST"
            echo "Post date: $POST_DATE"
            echo "Commit date: $COMMIT_DATE"

            # Compare post date to commit date
            if [ "$POST_DATE" == "$COMMIT_DATE" ]; then
              URL="https://www.pntaylor.net/$(basename ${POST%.*}).html"
              POST_URLS+="$URL"$'\n'
              echo "Post $POST is eligible for posting (same day)."
            else
              echo "Post $POST is too old."
            fi
          done

          if [ -z "$POST_URLS" ]; then
            echo "No posts with valid timestamps found. Exiting."
            exit 0
          fi

          echo "POST_URLS=$POST_URLS" >> $GITHUB_ENV

      - name: Post to Mastodon
        if: env.POST_URLS != ''
        run: |
          for URL in $(echo "$POST_URLS"); do
            toot post "New blog post: $URL"
          done
